### ISSUE TITLE
Implement shimmer animation

### ISSUE THREAD

**Issue by PranavVyas20** [gouravkhunger/QuotesApp#7]
Currently when a quote is loading, instead of using a progress bar to give animated effect, shimmer layout can be used.
Something like this:

![shimmer](https://user-images.githubusercontent.com/90063033/135855536-37cd4e64-88bf-40bc-a2da-d9d573381e41.jpg)

**Comment by gouravkhunger** [comment]
I fear that would look good on a colourful gradient background as it is now. The grey colour would look odd to be honest. And it is just 1 quote at a time on the QuotesFragment, this doesn't make sense to use shimmer instead of `ProgressDialog`.

Thanks a lot for your suggestion! But this doesn't seem feasible :)

**Comment by PranavVyas20** [comment]
> I fear that would look good on a colourful gradient background as it is now. The grey colour would look odd to be honest. And it is just 1 quote at a time on the QuotesFragment, this doesn't make sense to use shimmer instead of `ProgressDialog`.
> 
> Thanks a lot for your suggestion! But this doesn't seem feasible :)

No problem :)
